name: Build (stack)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, windows-2022]

    steps:
    - uses: actions/checkout@v4

    - uses: haskell-actions/setup@v2
      id: setup
      with:
        ghc-version: '9.8.2'
        stack-version: '2.15.5'
        enable-stack: true
        cabal-update: false

    - name: Restore cache from approximate key
      uses: actions/cache/restore@v4
      id:   cache
      with:
        path: ${{ steps.setup.outputs.stack-root }}
        key:  ${{ matrix.os }}-plan-${{ hashFiles('ci-stack-win.cabal', 'stack.yaml') }}
        restore-keys: |
              ${{ matrix.os }}-

    - run: stack build --system-ghc --fast --only-dependencies
    - run: stack build --system-ghc --fast
    - run: |
        stack run --system-ghc -- <<< 42

    - name: Save cache
      uses: actions/cache/save@v4
      if:   always() && steps.cache.outputs.cache-matched-key != steps.cache.outputs.cache-primary-key
      with:
        key:  ${{ steps.cache.outputs.cache-primary-key }}
        path: ${{ steps.setup.outputs.stack-root }}
