name: Build (stack)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, windows-2022]

    steps:
    - uses: actions/checkout@v4

    - uses: haskell-actions/setup@v2
      id: setup
      with:
        ghc-version: '9.8.2'
        stack-version: '2.15.5'
        enable-stack: true
        cabal-update: false

    - run: stack build --system-ghc --fast --only-dependencies
    - run: stack build --system-ghc --fast
    - run: |
        stack run --system-ghc --fast -- <<< 42
